events {}

http {

    upstream fastapi_servers {
        server localhost:8000;
    }

    server {

        listen 80;

        location / {
            proxy_pass http://fastapi_servers;
        }

    }

}